name: Run Maven Tests on PR

on:
  pull_request:
    branches:
      - main  # Adjust to match your main branch name in the chron repository

jobs:
  run_tests:
    name: Run Maven Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout chron repository
        uses: actions/checkout@v2
        with:
          repository: my9006/chron
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          
      - name: Run Maven Tests
        run: |
          git clone https://github.com/my9006/gideon.git
          cd gideon
          mvn -B test
