name: Run Docker Compose on PR

on:
  pull_request:
    branches:
      - main

jobs:
  run_docker_compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chron repo
        uses: actions/checkout@v2

      - name: Checkout gideon repo
        uses: actions/checkout@v2
        with:
          repository: my9006/gideon
          path: gideon

      - name: Run Docker Compose with Tests
        run: |
          cd gideon
          docker-compose up
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
          echo "::error::Docker Compose command failed with exit code $exit_code"
          exit $exit_code
          fi

      - name: Report Results
        run: |
          if [ ${{ steps.compose.outcome }} == 'success' ]; then
            echo "Tests passed successfully!"
          else
            echo "Tests failed!"
            exit 1
          fi
