name: Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  run_docker_compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chron repo
        uses: actions/checkout@v2

      - name: Checkout gideon repo
        uses: actions/checkout@v2
        with:
          repository: my9006/gideon
          path: gideon

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Run Maven tests
        run: mvn test
